{{- if and .Values.edgeProxy.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nofire-edge.edgeProxy.fullname" . }}
  namespace: {{ include "nofire-edge.serviceMonitorNamespace" . }}
  labels:
    {{- include "nofire-edge.edgeProxy.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nofire-edge.edgeProxy.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      path: /metrics
{{- end }}
