{{- if .Values.edgeProxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nofire-edge.edgeProxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nofire-edge.edgeProxy.labels" . | nindent 4 }}
{{- end }}
